version: '3.9'
services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/web-app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: centerpoint
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db:/var/lib/mysql
    ports:
      - 3306:3306
